framework:
    messenger:
        default_bus: command.bus
        buses:
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            asyncCommand.bus:
                middleware:
                    - validation

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Command\SourceSubjectDataCommand': async
            'App\Command\CreateIpCaseCommand': sync
            'App\DomainEvent\IpCaseCreated': sync
            'App\Query\FindIpCaseByIdQuery': sync
